# Generated by Django 5.2.6 on 2025-09-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_departamento_remove_residente_numero_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
